### ISSUE TITLE
Add new / modifying existent components to vocabulary according to new design

### ISSUE THREAD

**Issue by hugosolar** [cc-archive/vocabulary-legacy#17]
Since we are working on a major redesign, some of the components need to be modified and others need to be added

These changes are taking place in the `vocabulary-framework` branch

### Existent components
- [x] Modifying header - [view on Figma](https://www.figma.com/file/V0nHqFuIeWvXjOyyxfzFiT/Library-tests.-Internal-use?node-id=38%3A229)
- [ ] Modifying navigation
- [ ] Modifying footer - [view on Figma](https://www.figma.com/file/V0nHqFuIeWvXjOyyxfzFiT/Library-tests.-Internal-use?node-id=38%3A229)
- [ ] Modifying buttons
- [ ] Modifying forms
### Global menu
- [ ] Add global menu component - [view on Figma](https://www.figma.com/file/V0nHqFuIeWvXjOyyxfzFiT/Library-tests.-Internal-use?node-id=38%3A229)
### Entries - [view on Figma](https://www.figma.com/file/V0nHqFuIeWvXjOyyxfzFiT/Library-tests.-Internal-use?node-id=145%3A0)
- [ ] Post
- [ ] Event
- [ ] Video
- [ ] Person
- [ ] stats

**Comment by dhruvkb** [comment]
Can you please post the link to the design docs or Figma files here? It would be helpful to have the resource with the issue.

Also, I hope you will sync the changes to [creativecommons/vue-vocabulary](https://github.com/creativecommons/vue-vocabulary). That's because Vue Vocabulary is constantly being updated thanks to Outreachy and new GSoC aspirants and this repo has already gotten behind in syncing those changes.

**Comment by kgodey** [comment]
@dhruvkb could you document somewhere the current workflow for making changes to these repos while they still have duplicated code?

**Comment by hugosolar** [comment]
Closing this in favor of new individual issues recently created
