### ISSUE TITLE
Change the hover style of basic links

### ISSUE THREAD

**Issue by fcoveram** [cc-archive/vocabulary-legacy#243]
Currently, the hover state of links changes the text color from tomato to black. This must change to just adding an underline style instead of changing the text color.

### Currently
<img width="244" alt="Screen Shot 2020-03-24 at 16 07 45" src="https://user-images.githubusercontent.com/895819/77466837-a3bb7380-6de9-11ea-9e65-305002bfe818.png">

### Expected
<img width="734" alt="Screen Shot 2020-03-24 at 16 07 34" src="https://user-images.githubusercontent.com/895819/77466826-9e5e2900-6de9-11ea-8836-6d6fe26d7eaf.png">

**Comment by silvinabt87** [comment]
Hi @kgodey @panchovm if there's nobody working on this, I'd like to contribute!

**Comment by kushaggarwal** [comment]
Hello @kgodey @panchovm I have made the changes as described above in the issue but not able to link the pull request due to the fact that the issue no. doesnt match please help
here is the screenshot for the same 
![Screenshot 2020-03-26 at 2 08 30 AM](https://user-images.githubusercontent.com/44523552/77583228-b8d9f480-6f06-11ea-94ba-d373bf6344a2.png)

**Comment by kushaggarwal** [comment]
Can you please help as not able to make out that the changes need to be made in the cccatalog-frontend or vocabulary for this particular issue 
@panchovm @kgodey @dhruvkb 
Please help

**Comment by SaurabhAgarwala** [comment]
> Can you please help as not able to make out that the changes need to be made in the cccatalog-frontend or vocabulary for this particular issue
> @panchovm @kgodey @dhruvkb
> Please help

Hi @kushaggarwal. Since this issue has been moved to vocabulary repo, so to address this issue you will have to use its complete URL instead of just the #XXX in the PR which you are going to create in the cccatalog-frontend repo. This will create the required link between the issue and the PR. Hope this helps.

And, in case, if you are not further working on this issue then please do let me know. I am interested to work on this.

**Comment by kushaggarwal** [comment]
Actually I have worked out the changes for this issue but wasnt able to put a pull request for the same but @SaurabhAgarwala thank you very much for your help as I feel now I can open one

**Comment by SaurabhAgarwala** [comment]
> Actually I have worked out the changes for this issue but wasnt able to put a pull request for the same but @SaurabhAgarwala thank you very much for your help as I feel now I can open one

@kushaggarwal Glad, I could help :)

**Comment by nehasangeetajha** [comment]
Is this issue open? I would like to work of it is

**Comment by kushaggarwal** [comment]
Actually @nehasangeetajha I have already linked a pull request for the same above
