### ISSUE TITLE
Edit breakpoints for large header.

### ISSUE THREAD

**Issue by Dhruvi16** [cc-archive/vocabulary-legacy#438]
## Problem Description

The header can be large in some cases (ex. CCOS). And in such case, the header breaks between 1024px (desktop) and 1408px (fullhd). 

## Solution Description

One solution can be changing the breakpoint in Bulma from $desktop to $fullhd so we get the burger menu up till 1408px.

**Edit:** This will be fixed temporarily by reducing the spacing between menu items and the font size for screens between 1024px (desktop) and 1408px.

**Comment by Dhruvi16** [comment]
Tagging @hugosolar @dhruvkb @panchovm for discussion.

**Comment by fcoveram** [comment]
Can you attach a screenshot of how it breaks?

**Comment by Dhruvi16** [comment]
![image](https://user-images.githubusercontent.com/34674462/83923644-4dcb5a80-a7a0-11ea-9b4b-df7e32182421.png) 
1112px

![image](https://user-images.githubusercontent.com/34674462/83923711-6e93b000-a7a0-11ea-9087-f8bec75afb49.png)
1220px

**Comment by fcoveram** [comment]
I see. The **archives** item disappears. I think we can reduce the margin between elements and define a breakpoint where changes to the mobile menu. What do you think @dhruvkb @hugosolar?

**Comment by dhruvkb** [comment]
This is hard to determine because it will change with the number of items in the menu. Maybe we should have an upper limit on the number of top-level menu items and if it exceeds that limit, the menu should be re-organised.

**Comment by fcoveram** [comment]
I see. It makes sense what you say. Just adding two comments:
1. I remember that the component had some style problems (ticket #374). Maybe those corrections have not been applied and, therefore, it influences this bug.
2. We will always have a risk of breaking because of length characters in items. So I assume that in future sites we might open the discussion again.

But in general, I agree with limiting the number of items. However, in this case, we can not reduce them. That's why my suggestion is to reduce the margin between elements.

**Comment by dhruvkb** [comment]
In that case, instead of hard-coded margins, we should be using a flex layout with the `justify-content: space-between` property so that it can look reasonably well-spaced for a reasonable number of items.

**Comment by Dhruvi16** [comment]
I agree with @dhruvkb here.

**Comment by kgodey** [comment]
@panchovm is exploring fixing this in the new header design

**Comment by Dhruvi16** [comment]
I think this was just a temporary fix so we should not close this.

**Comment by kgodey** [comment]
Closing in favor of https://github.com/creativecommons/vocabulary/issues/620
