### ISSUE TITLE
Small version of source cards [Feature request]

### ISSUE THREAD

**Issue by makkoncept** [cc-archive/vocabulary-legacy#482]
## Descriptions

In the [Mockup](https://www.figma.com/file/nJk4krHryIjzYGvaioMsAu/Browser-extension?node-id=892%3A4562) of CC Search Extension, the cards that are used to contain each source in the "Sources" section is the same as the cards present on [Collections page of CC Search](https://search.creativecommons.org/collections) but are relatively smaller in size.

Pasting the mockup screenshot for reference.

![Screenshot from 2020-06-18 19-12-19](https://user-images.githubusercontent.com/34679965/85027620-bf8ba700-b197-11ea-9095-64d718cf4bd3.png)

## Implementation

- [ ] I would be interested in implementing this feature.

**Comment by zackkrida** [comment]
@makkoncept We are actually going to be changing the 'Collections' page on CC Search, and no longer using these cards. What actually makes these cards distinct isn't that they are smaller, but that the images are _larger_ than the cards on the current Collections page. We may be able to change the image size of _all cards_ instead of to creating a 'small' variation of the cards. @panchovm, do you have thoughts on this?

**Comment by fcoveram** [comment]
You are right @zackkrida, we will get rid of those cards because we're changing the content and how we treat sources and providers. It is an important change that impacts CC Search as a product, and it makes sense to update this page to match the new design.

This is [the new design](https://www.figma.com/file/y09nZth7u1a75xO9sLtjcw/Mockup---S5-(Source-and-provider)?node-id=205%3A5130&viewport=142%2C73%2C0.6530460715293884) and, as you can see, we are using a single table. The use of logos is a problem for now.

**Comment by makkoncept** [comment]
Thanks, @zackkrida and @panchovm for the update. I'll close this. Also, @panchovm I currently don't have the permission to view the Figma file you linked.

**Comment by fcoveram** [comment]
Sorry @makkoncept. Please check again.

**Comment by makkoncept** [comment]
@panchovm Got the invite :100: . Thanks!
