### ISSUE TITLE
CalVer and CDN compatibility

### ISSUE THREAD

**Issue by zackkrida** [cc-archive/vocabulary-legacy#588]
Because npm automatically parses and rewrites our version numbers from `2020.08.4` to `2020.8.4` it makes it difficult for users to find the correct version on the cdn. If they try to go to a url like:

https://unpkg.com/@creativecommons/vocabulary@2020.08.4 (note the `08`)

it fails, although

https://unpkg.com/@creativecommons/vocabulary@2020.8.4 

works fine

**Comment by dhruvkb** [comment]
_One zany thing about this is that it will work for three months every year._ On a serious note, I have serious doubts that `npm` will change their versioning logic because that could potentially break a lot of other packages that are deployed to it. It largely falls on us to not use leading zeros in our versions.

**Comment by zackkrida** [comment]
Yes, I think we should just revise our CalVar implementation to remove the leading zero from the month so its compatible with semver. I think we should do this for any JavaScript projects using CalVer for consistency.

**Comment by kgodey** [comment]
Sounds good to me.
