### ISSUE TITLE
Line break issue in `card` components

### ISSUE THREAD

**Issue by Aakash2408** [cc-archive/vocabulary-legacy#601]
@kgodey 
## Description
  
    One of the featured proejct's content gets out  of the box when checked the responsiveness.

## Expectation
The content should remain inside the box on every dimensions.

## Screenshots
![Screenshot from 2020-08-21 02-56-46](https://user-images.githubusercontent.com/47134609/90847717-abf8ea00-e35a-11ea-8909-7380b0843cd1.png)
![Screenshot from 2020-08-21 02-56-35](https://user-images.githubusercontent.com/47134609/90847763-c632c800-e35a-11ea-8737-b4ff2423bd75.png)

## Resolution

- [x] I would be interested in resolving this bug.

**Comment by Dhruvi16** [comment]
I think we should move this issue to Vocabulary.

**Comment by kgodey** [comment]
@Dhruvi16 go ahead

@Aakash2408 the CSS for this component lives in Vocabulary, our design system, so we'll move the issue to that repo.

**Comment by Aakash2408** [comment]
so is @Dhruvi16 doing this or i can take this?

**Comment by Dhruvi16** [comment]
You can go ahead @Aakash2408 .

**Comment by Aakash2408** [comment]
Thanks!😅

**Comment by Aakash2408** [comment]
@Dhruvi16 its code is in this repo or the other one i.e, creativecommons source

**Comment by Aakash2408** [comment]
@kgodey ?

> @Dhruvi16 its code is in this repo or the other one i.e, creativecommons source

**Comment by zackkrida** [comment]
@Aakash2408 the card styles can [be found here](https://github.com/creativecommons/vocabulary/blob/master/src/styles/card.scss)

also, you don't need to tag @ kgodey she automatically gets notifications anyway 😆

**Comment by Aakash2408** [comment]
How to run this project in local environment?

**Comment by Dhruvi16** [comment]
Hey @Aakash2408 sorry for the late response. Here is the [contributing guide](https://cc-vocabulary.netlify.app/?path=/docs/vocabulary-contribution--page).

**Comment by kgodey** [comment]
@Aakash2408 looks like you got your answer, but in the future, please be patient 🙂. we all have a lot to do and it can take us up to a couple of days to answer questions, repeatedly pinging us will not help.

**Comment by Aakash2408** [comment]
@Dhruvi16  sorry I was not able to check the code past few days due to some tests.I will surely check the code today .Thanks for assigning it  to me.

**Comment by heykc** [comment]
Wanted to check in and see if this still needs to be worked on. If so I can jump on this and knock it out ✌

**Comment by kgodey** [comment]
go ahead @heykc

**Comment by heykc** [comment]
I didn't want to put this up for review just yet because I have a question. These changes that I made to the button.scss file *could* be made and the fix would be implemented, however, I do think there's some weight in suggesting that the language of the button elements themselves be revisited. The name of the slack channels are listed in the buttons themselves, but how necessary is this? 

By removing the additional name (so having it only say "slack channel") and also removing what seems like some superfluous padding on the right of each card element (note: the added padding-right is not coming from the vocabulary library), this issue would resolve itself without ever having to edit any styling from vocabulary directly.

I'm not sure which option sounds more appropriate, but if you feel allowing line breaks for .tag and .is_text buttons is necessary, then I will change the status of my PR to ready for review 😃

**Comment by zackkrida** [comment]
I'm personally into the idea of hiding the channel names. But, I also think we need to think about handling multi-line buttons in vocabulary. Is that something we think we need to support? Especially considering i18n, where some translations are much longer than the original English.

I would say, yes! make your button pull request, but maybe we'll shorten the channel names too 😆

**Comment by hugosolar** [comment]
I agree with @zackkrida we need to think in multi-line buttons and maybe for others elements too. Also, I'm in favor of hiding channel names 😄

**Comment by heykc** [comment]
PR is ready for review! Wasn't sure if I should ask this question here or directly in the PR, but would it make sense to have a .multi-line class for buttons rather than only making these changes to .tag and .is-text classes? that way we can have this feature across all buttons depending on use case.
