### ISSUE TITLE
Monorepo Documentation

### ISSUE THREAD

**Issue by zackkrida** [cc-archive/vocabulary-legacy#627]
Now that the monorepo is live we should create a storybook page explaining the monorepo structure and the rationale behind it.

We should link to this page in the README here: [creativecommons/vocabulary#included-packages](https://github.com/creativecommons/vocabulary#included-packages)

**Comment by nimishbongale** [comment]
Will work on this!

**Comment by nimishbongale** [comment]
@zackkrida 

My initial thought was that the justification for the monorepo would be a part of the unified landing site, rather than just being a standalone `MONOREPO.md` within the repository. In either case, I have the document ready in our shared drive as a markdown file.

Do let me know if that's okay!

**Comment by zackkrida** [comment]
@nimishbongale I would love to do both. I'd like this section to be able to link down to a markdown file: https://github.com/creativecommons/vocabulary#included-packages

**Comment by dhruvkb** [comment]
Managing identical text in two separate documents is not good. @zackkrida couldn't the `README.md` contain the link to the page instead?

**Comment by nimishbongale** [comment]
The monorepo part is now included in the landing site. However, since it is a single page site, adding in too many technical details on it would not be the wisest imo. Could we instead have the detailed explanation to _"Vocabulary, Monorepo?" section_ as a part of the storybook (or this repository) and I could link it accordingly perhaps?

**Comment by dhruvkb** [comment]
I agree that it would be wise to keep the technicalities to the Storybook.
