### ISSUE TITLE
npm ERR! missing script: build

### ISSUE THREAD

**Issue by brylie** [cc-archive/vocabulary-legacy#963]
Our CI pipeline is failing with the following error:

> Run npm run lint
> npm ERR! missing script: build

## Task

- [ ] create or restore the `build` command so unit tests will run during pull requests
- [ ] the `build` command should run all other build commands across the `fonts`, `vocabulary`, and `vue-vocabulary` packages where relevant

**Comment by MuluhGodson** [comment]
I will love to take this issue and #961  since it involves refactoring the same files (The CI) files.

**Comment by MuluhGodson** [comment]
@brylie I forgot to add a whitespace in the CD files and that is causing some problems:
https://github.com/creativecommons/vocabulary/actions/runs/1336635934/workflow

instead of `- name` I wrote `-name` so I am requesting to correct that in the PR that will linked to this issue since it's not a big change.

**Comment by brylie** [comment]
I've fixed the typos in the CD files.

**Comment by MuluhGodson** [comment]
Okay great. Thank you.

**Comment by MuluhGodson** [comment]
It goes also for the other two cd files

**Comment by brylie** [comment]
I've re-read the three CD files and can't see any remaining typos. Are there any typos that you can spot?

**Comment by MuluhGodson** [comment]
All have been fixed.
